buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22"
        classpath "org.springframework.boot:spring-boot-gradle-plugin:3.1.5"
        classpath "io.spring.gradle:dependency-management-plugin:1.1.7"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
